name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liX0pAo8WTRzYEsF"
GITHUB_OWNER = "kingszzj"
GITHUB_REPO = "Nav"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsphere-6fz.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://www.userc.org"

